import dynamic from "next/dynamic";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import ProgressBar from "@/components/ProgressBar/ProgressBar";
import ProgressBarProvider from "@/components/ProgressBar/ProgressProvider";
import ProgressWatcher from "@/components/ProgressBar/ProgressBarWatcher";

const StoreProvider = dynamic(() => import("../providers/StoreProvider"));
const ThemeProvider = dynamic(() => import("@/providers/ThemeProvider"));
const ToastProvider = dynamic(
  () => import("@/components-system/toast/ToastProvider")
);
// import ToastProvider from "@/components-system/toast/ToastProvider";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // chọn các độ đậm bạn cần
  variable: "--font-roboto", // optional, dùng cho Tailwind
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.variable}`}>
        {/* <StoreProvider> */}
        <ProgressBarProvider>
           <ProgressBar/>
           <ProgressWatcher/>
          <ToastProvider>
            <ThemeProvider>{children}</ThemeProvider>
          </ToastProvider>
        </ProgressBarProvider>

        {/* </StoreProvider> */}
      </body>
    </html>
  );
}
